teach-me:
  sessionSize: 10
  sessionUrl: session
  sessionAllUrl: sessionAll
  conceptsUrl: concepts2

server:
  address: 0.0.0.0
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ${TEACH_ME_CERT_PASS}
#    keyStoreType: PKCS12
#    keyAlias: tomcat

#logging:
#  level:
#    ROOT: DEBUG

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}  #jdbc:postgresql://localhost/teachme
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    platform: POSTGRESQL
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate

---
spring:
  profiles: hsqldb
  datasource:
    driverClassName: "org.hsqldb.jdbc.JDBCDriver"
    url: "jdbc:hsqldb:file:db/teach-me"
    user: "SA"
    password: ""
  jpa:
    database: HSQL
    hibernate:
      ddl-auto: validate
